#pragma once

namespace Carbon
{
	namespace Compiler
	{
		// all token types generated by the lexer
		enum class Token
		{
			// most important
			Id,
			FileEnd,
			FileBegin,

			// string datatypes
			StringUnicode,
			StringBinary,
			String,

			// numeric datatypes
			Float,
			NumberHexadecimal,
			NumberBinary,
			NumberOctal,
			Number,

			// syntax symbols

			EndStatement,

			// operators

			Equals,
			NotEquals,
			LessOrEqual,
			GreaterOrEqual,
			Assign,
			Less,
			Greater,
			Add,
			Subtract,
			Multiply,
			Divide,
			Member,

			// keywords

			Function,
			Loop,
			Else,
			If,
			Then,
			Local,
			Break,
			Continue,
			Return,
		};

	}
}