name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Zig Compiler
      uses: mlugg/setup-zig@v1.2.1
      with:
        version: 0.13.0
        use-cache: true

    - name: Build
      run: bash ./build.sh multitarget

    - name: Test
      run: bash ./test.sh
      
    - uses: actions/upload-artifact@v4.4.3
      with:
        path: ./out/
