name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh
      
    - uses: actions/upload-artifact@v4.4.3
      with:
        path: ./out/carbon

  
